### PR TITLE
Add config loading package

### PR DESCRIPTION
**Pull request by pete-woods**

### CODE REVIEW

**Comment by erickim-circleci** [comment]
I noticed that you've changed test verification from `assert.Equal` to `assert.Check`. Is there a reason why you prefer the latter?

**Comment by erickim-circleci** [comment]
also, the convention for Go's `assert` generally is to have expected values come first (example: https://pkg.go.dev/github.com/stretchr/testify/assert#Equal) but we have it the other way around. Is this our agreed convention?

**Comment by pete-woods** [comment]
> also, the convention for Go's `assert` generally is to have expected values come first (example: https://pkg.go.dev/github.com/stretchr/testify/assert#Equal) but we have it the other way around. Is this our agreed convention?

The library we use takes a completely agnostic view to this, referring to them as `x`, `y` (I also don't feel particularly strongly)

**Comment by pete-woods** [comment]
> I noticed that you've changed test verification from `assert.Equal` to `assert.Check`. Is there a reason why you prefer the latter?

`assert.Check` is a soft assertion, whereas `assert.Assert` is a hard assertion. Hard assertions fail immediately, while soft ones will allow the test to continue, gathering up as much information as possible.

The top level functions like `assert.Equal` all internally delegate to `assert.Assert`, so they are all hard assertions.

I would only use a hard assertion where proceeding further in the test would cause a panic, or some other failure making progress of no value.

e.g. you often do `assert.Assert(t, err)` if the error means that a returned value was `nil`, for example.

**Comment by pete-woods** [comment]
@erickim-circleci if you're looking at this, a stamp would be much appreciated!

**Review by bjohnso5 — APPROVED** [review]

**Pull request merged**
