### PR TITLE
[TASKS-871] Allow attaching decoders to http errors

### PR DESCRIPTION
**Pull request by MaT1g3R**

### CODE REVIEW

**Review by bjohnso5 — APPROVED** [review]

**Comment by pete-woods** [comment]
Can we easily add a decoder for 2xx? 3xx 5xx?

**Comment by pete-woods** [comment]
I feel like I would like to treat any of those groups the same, rather than having to enumerate large numbers of codes

**Comment by pete-woods** [comment]
I think most services should be designed to respond with a similar json payload for those categories of error codes.

**Comment by MaT1g3R** [comment]
I can see treating 2xx as the same group, but there might be different cases for 4xx that you would like to handle differently. I think usually you are probably looking to handle 1 case of 4xx specifically.

**Pull request merged**
