### PR TITLE
[TASKS-903]       `httpclient` Allow setting raw body

### PR DESCRIPTION
**Pull request by MaT1g3R**
- `httpclient` Allow setting raw body

### CODE REVIEW

**Comment by pete-woods** [comment]
Is this no good? https://github.com/gin-contrib/gzip

**Comment by danmux** [comment]
gzipping request bodies is unusual enough that I would leave it out.

but add an optionfunc for set the body and content type if we are starting to send anything other than json in the request

**Comment by MaT1g3R** [comment]
I'm not sure if it's unusual, we are going to immediately need it to proxy job submit

**Comment by MaT1g3R** [comment]
> Is this no good? https://github.com/gin-contrib/gzip

No, it requires a custom unzip function, so it basically does nothing

**Comment by danmux** [comment]
> I'm not sure if it's unusual, we are going to immediately need it to proxy job submit

Why? for the proxying we can just read the []bytes in the gateway handler - and write the bytes with your new client code in here.

When we want gateway to decode the payload we can just unzip it in the handler 

In 25 years of development - distributor is the only place I have ever seen a handler need to unzip a json payload (i've seen manny that opaquely pass on the gzipped content to storage) 

I think that is also the reason why the vast majority of middleware out there only includes gzipping the response. (as per https://github.com/gin-contrib/gzip)

Imo this is a special case in the gateway, and distributor, and they should handle it, and it should not go into `ex`

the distributor `MaybeGunzip` should not even be in the middleware package - and should be moved to a private method near the jobSubmit handler, and copied into the gateway.

**Review by danmux — APPROVED** [review]

**Comment by pete-woods** [comment]
Proxying should use httputil.Proxy anyway, in general

**Pull request merged**
