### PR TITLE
Do not panic on bad honeycomb keys

### PR DESCRIPTION
**Pull request by MaT1g3R**
- o11y formatting errors should not page, we will format the keys properly instead

### CODE REVIEW

**Review by pete-woods — COMMENTED** [review]
The reason it's like this, is to make it so you can guarantee what you see in honeycomb / logs is exactly what's in the code

**Comment by MaT1g3R** [comment]
true, but i wouldn't want to get woken up by this

**Comment by danmux** [comment]
> true, but i wouldn't want to get woken up by this

Yep, thats fair - the intention was it would fail loudly in testing. But in the recent case the exception path was not hit in a test.

I wonder if there is some tooling we could add to catch these instead?

**Comment by MaT1g3R** [comment]
If only we could catch these at compile time :grinning:

**Comment by ProjectFrank** [comment]
@MaT1g3R could you provide some context as to what happened when you were paged for something related to this? A link to the PR containing the bad honeycomb keys would be helpful.

**Comment by pete-woods** [comment]
> @MaT1g3R could you provide some context as to what happened when you were paged for something related to this? A link to the PR containing the bad honeycomb keys would be helpful.

I think what happened was there was an o11y span created *only* on an error path, and it had a `-` in the attributes. Normally spans are created around each function, and so it's hard even with limited testing, to avoid hitting them, and then you get a panic right away.

**Pull request closed without merging**
